const autofilterConfig = {
    imageSrc: '/images/explorers/ableton-autofilter.png',
    imageAlt: 'Ableton Live Auto Filter effect interface showing filter type, slope, frequency, resonance and sidechain controls',
    title: 'Auto Filter Controls Explorer',
    instruction: 'Drag a cable from the floating box to a coloured zone below the image to learn what that control does.',
    daw: 'Ableton Live',
    dawNote: 'Every DAW has a filter; this one is Ableton Live\'s Auto Filter device. The concepts — cutoff frequency, slope, resonance — are the same wherever you find them.',
    hotspots: [
        {
            id: 'sidechain',
            label: 'A',
            zone: { left: 0, width: 15 },
            color: '#E8590C',
            level: 'advanced',
            name: 'Sidechain',
            matchClue: 'Routes a separate audio source to trigger the filter, rather than the signal being processed itself.',
            description: 'Enables sidechain filtering, where an external signal controls the filter behaviour instead of the signal being processed. For example, routing a kick drum to trigger the Auto Filter on a pad means the filter responds to the kick\'s dynamics rather than the pad itself. The {{D}} frequency still sets the base cutoff — sidechain only changes what signal drives the envelope follower.',
            questions: [
                { q: 'When would I use sidechain on a filter?', a: 'Sidechain filtering is used to create rhythmic filter effects driven by another element. A common technique is routing a kick drum to trigger a low-pass filter on a bass synth — the filter opens on each kick hit, creating a pumping, rhythmic effect that locks the bass to the groove. It is also used for creative ducking effects on pads and textures.' },
                { q: 'How is sidechain filtering different from sidechain compression?', a: 'Sidechain compression reduces volume when the external signal is loud. Sidechain filtering moves the {{D}} cutoff frequency when the external signal is loud — the audio is still present, but its tonal character changes. This can be more subtle and musical than simple volume ducking.' },
            ],
        },
        {
            id: 'filter-type',
            label: 'B',
            zone: { left: 15, width: 18 },
            color: '#D97706',
            level: 'foundation',
            name: 'Filter Type',
            matchClue: 'The drop-down menu that selects whether the filter is low-pass or high-pass.',
            description: 'Selects the type of filter. A low-pass (LP) filter lets frequencies below the {{D}} cutoff through and removes frequencies above it — useful for removing brightness or creating a muffled effect. A high-pass (HP) filter does the opposite, letting frequencies above the cutoff through and removing those below — essential for removing unwanted low-frequency rumble and mud.',
            questions: [
                { q: 'When would I use a low-pass filter?', a: 'Low-pass filters are used to remove high frequencies. Common uses: softening a harsh synth, creating a "muffled" or "underwater" effect, simulating distance (distant sounds have less high frequency content), and classic dance music filter sweeps where the low-pass gradually opens to build energy. Set the {{D}} frequency to control where the cut begins.' },
                { q: 'When would I use a high-pass filter?', a: 'High-pass filters are one of the most important mixing tools. Use them to remove low-frequency rumble, handling noise, and mud from signals that do not need bass content — vocals, guitars, hi-hats, and overheads. Setting the {{D}} frequency to around 80-120 Hz on most non-bass instruments cleans up the low end of a mix significantly.' },
                { q: 'What is the difference between low-pass and high-pass?', a: 'Think of the name as describing what passes through. Low-pass: low frequencies pass, high frequencies are cut. High-pass: high frequencies pass, low frequencies are cut. A low-pass filter with the {{D}} cutoff at 5 kHz removes everything above 5 kHz. A high-pass filter at 100 Hz removes everything below 100 Hz.' },
            ],
        },
        {
            id: 'slope',
            label: 'C',
            zone: { left: 33, width: 14 },
            color: '#059669',
            level: 'foundation',
            name: 'Slope (12/24)',
            matchClue: 'Controls how steeply the filter cuts frequencies beyond the cutoff point.',
            description: 'The slope determines how aggressively the filter removes frequencies beyond the {{D}} cutoff, measured in dB per octave. A 12 dB/octave slope is gentler — frequencies beyond the cutoff fade away gradually, allowing some through. A 24 dB/octave slope is steeper — it cuts much more sharply, creating a more dramatic and defined filtering effect.',
            questions: [
                { q: 'What does "dB per octave" mean?', a: 'It describes how quickly the signal level drops as you move further from the {{D}} cutoff frequency. An octave is a doubling of frequency. With a 12 dB/octave low-pass filter set at 1 kHz, frequencies at 2 kHz (one octave above) are reduced by 12 dB, and at 4 kHz (two octaves above) by 24 dB. A 24 dB/octave slope reduces twice as fast — 24 dB at one octave, 48 dB at two octaves.' },
                { q: 'When should I use 12 versus 24?', a: 'Use 12 dB/octave for subtle, natural-sounding filtering — the gentler slope lets some content through, which sounds less obvious. Use 24 dB/octave when you want a more defined, "electronic" filter sound, or when you need to remove unwanted frequencies more completely. Classic analogue synthesiser filters are typically 24 dB/octave (also called a 4-pole filter).' },
                { q: 'What is the difference between a 2-pole and 4-pole filter?', a: 'Each "pole" adds 6 dB/octave of slope. A 2-pole filter has a 12 dB/octave slope; a 4-pole filter has a 24 dB/octave slope. These terms come from the electronic circuit design. The 12 dB selector in Ableton is a 2-pole filter, and the 24 dB selector is a 4-pole filter. You may see these terms used interchangeably in synthesiser manuals.' },
            ],
        },
        {
            id: 'frequency',
            label: 'D',
            zone: { left: 47, width: 28 },
            color: '#2563EB',
            level: 'foundation',
            name: 'Frequency',
            matchClue: 'The cutoff frequency — where the filter begins to take effect.',
            description: 'Sets the cutoff frequency for the filter. For a low-pass {{B}} filter type, frequencies above this point are removed. For a high-pass filter, frequencies below this point are removed. This is the most important control on the filter — it determines which frequencies are kept and which are cut. Moving the frequency creates the classic "filter sweep" sound.',
            questions: [
                { q: 'What happens when I sweep the frequency?', a: 'Sweeping the frequency moves the cutoff point across the spectrum in real time. On a low-pass filter, sweeping up gradually reveals the high frequencies — this is the classic "filter opening" sound used in dance music buildups. Sweeping down closes the filter, muffling the sound. The speed and range of the sweep determine the dramatic effect.' },
                { q: 'How does frequency interact with resonance?', a: 'The {{E}} resonance boosts frequencies right at the cutoff point. When you sweep the frequency with resonance turned up, you hear a pronounced peak moving through the spectrum — this is the classic "wah" or "squelchy" filter sound. Without resonance, the sweep is smoother and more subtle.' },
                { q: 'What frequency range should I set for different uses?', a: 'For removing low-end rumble with a high-pass filter, set the cutoff between 80-150 Hz. For a muffled "underwater" low-pass effect, try 500-1000 Hz. For gentle high-frequency taming, set a low-pass around 8-12 kHz. For creative filter sweeps, automate the full range. The right setting depends on the source material and the effect you want.' },
            ],
        },
        {
            id: 'resonance',
            label: 'E',
            zone: { left: 75, width: 25 },
            color: '#9B7530',
            level: 'foundation',
            name: 'Resonance',
            matchClue: 'Boosts frequencies at the cutoff point, adding emphasis or a peak to the filter.',
            description: 'Also called Q, resonance boosts a narrow band of frequencies right at the {{D}} cutoff frequency. Low resonance gives a smooth, gentle filter effect. High resonance creates a sharp peak that adds character — the classic "squelchy" or "acidic" filter sound heard in electronic music. At very high settings, the filter can self-oscillate, producing a pure sine tone at the cutoff frequency.',
            questions: [
                { q: 'What is self-oscillation?', a: 'When resonance is pushed to maximum, the feedback at the {{D}} cutoff frequency becomes so strong that the filter produces its own tone — a pure sine wave — even with no input signal. This is called self-oscillation. Some classic analogue synthesisers use this as a sound source. It happens because the resonance feeds the output back into the input, creating a loop.' },
                { q: 'How much resonance should I use?', a: 'It depends on the effect. For subtle tone shaping and mixing use, keep resonance low (under 20%) — the filter cuts cleanly without adding a peak. For a pronounced filter character like acid bass lines or dubstep wobbles, go higher (50-80%). For aggressive, screaming effects, push it near maximum. Always listen in context — high resonance can make a sound piercing in a mix.' },
                { q: 'Is resonance the same as Q on a parametric EQ?', a: 'They describe a similar concept — the emphasis or narrowness at a specific frequency — but in different contexts. On a filter, resonance is a boost at the cutoff point that adds character and emphasis. On a parametric EQ, Q describes how wide or narrow the affected frequency band is. Both relate to the "sharpness" of the frequency response at a specific point.' },
            ],
        },
    ],
};

export default autofilterConfig;
