const compressorConfig = {
    imageSrc: '/images/explorers/ableton-compressor.png',
    imageAlt: 'Ableton Live Compressor effect interface showing threshold, ratio, attack, release, makeup gain, and knee controls',
    title: 'Compressor Controls Explorer',
    instruction: 'Drag a cable from the floating box to a coloured zone below the image to learn what that control does.',
    hotspots: [
        {
            id: 'external',
            label: 'A',
            zone: { left: 0, width: 13 },
            color: '#E8590C',
            level: 'advanced',
            name: 'External (Sidechain)',
            matchClue: 'Routes a separate audio source to trigger the processing, rather than the signal being processed itself.',
            description: 'Enables sidechain compression, where the compressor listens to an external signal (the "key" or "trigger") instead of the signal it is compressing. For example, a kick drum can trigger compression on a bass synth, causing it to duck in volume each time the kick hits. The {{B}} threshold and {{C}} ratio still control the compression — sidechain only changes what signal triggers it.',
            questions: [
                { q: 'When would I use sidechain compression?', a: 'Sidechain compression is most commonly used to make space for a kick drum in a mix. By routing the kick to trigger compression on the bass or a synth pad, those elements duck out of the way each time the kick hits. Set a fast {{D}} attack so the compressor reacts instantly to each kick, and adjust the {{E}} release to control how quickly the volume returns.' },
                { q: 'What signal do I route to the sidechain input?', a: 'You route the signal you want to use as the trigger — typically a kick drum, but it could be any element. In Ableton, set the "Sidechain" source dropdown to the track you want to trigger from. The compressor then reacts to that external signal rather than the audio on its own track.' },
                { q: 'How is this different from normal compression?', a: 'In normal compression, the compressor reacts to the signal it is processing — the {{B}} threshold detects peaks in the same audio. With sidechain, it reacts to a completely different signal. The audio being compressed may be quiet or loud — it doesn\'t matter. What matters is the level of the external trigger signal.' },
            ],
        },
        {
            id: 'threshold',
            label: 'B',
            zone: { left: 14, width: 14 },
            color: '#D97706',
            level: 'foundation',
            name: 'Threshold',
            matchClue: 'The level above which the compressor begins to act on the signal.',
            description: 'Sets the level (in dB) above which compression begins. Signals below this level pass through unaffected. A lower threshold means more of the signal gets compressed — the {{C}} ratio then determines how much those louder signals are reduced. After compressing, use {{G}} makeup gain to restore the overall volume.',
            questions: [
                { q: 'What happens if I set the threshold too low?', a: 'If the threshold is set very low, almost all of the signal will exceed it, meaning the compressor is working constantly. This can make the sound feel squashed and lifeless, removing all the natural dynamics. You lose the contrast between quiet and loud moments.' },
                { q: 'How do I choose the right threshold?', a: 'Watch the gain reduction meter while playing back. A good starting point is to set the threshold so you see 3-6 dB of gain reduction on the loudest peaks. This tames the peaks without over-compressing. Adjust by ear — if it sounds flat, raise the threshold.' },
                { q: 'Does threshold affect the tone of the sound?', a: 'Not directly — threshold only determines when compression starts. However, by controlling how much of the signal gets compressed, it indirectly shapes the overall dynamic feel. A lower threshold combined with a high {{C}} ratio can dramatically change the perceived character of a sound.' },
            ],
        },
        {
            id: 'ratio',
            label: 'C',
            zone: { left: 29, width: 13 },
            color: '#059669',
            level: 'foundation',
            name: 'Ratio',
            matchClue: 'Determines how much gain reduction is applied to the signal that exceeds the set level.',
            description: 'Determines how much the signal is reduced once it exceeds the {{B}} threshold. A 4:1 ratio means for every 4 dB the signal goes over the threshold, only 1 dB comes through. Higher ratios (10:1+) approach limiting, where the signal is almost completely prevented from exceeding the threshold.',
            questions: [
                { q: 'What ratio should I use for vocals?', a: 'For vocals, a ratio between 2:1 and 4:1 is typical. 2:1 gives gentle, transparent compression that controls dynamics without being obvious. 4:1 is more assertive and helps a vocal sit consistently in a dense mix. Go higher (6:1+) only for aggressive styles or spoken word. Pair with a soft {{F}} knee for a natural, transparent feel.' },
                { q: 'What is the difference between compression and limiting?', a: 'Limiting is essentially extreme compression. A limiter uses a very high ratio (typically 10:1 or higher, often infinity:1) with a fast {{D}} attack, creating a hard ceiling that the signal cannot exceed. A compressor with a ratio above 10:1 is effectively acting as a limiter.' },
                { q: 'Does a higher ratio always mean more compression?', a: 'A higher ratio means stronger compression on the signal that exceeds the {{B}} threshold, but how much compression you actually hear depends on the threshold too. A 10:1 ratio with a very high threshold might compress less audibly than a 2:1 ratio with a very low threshold.' },
            ],
        },
        {
            id: 'attack',
            label: 'D',
            zone: { left: 43, width: 13 },
            color: '#2563EB',
            level: 'foundation',
            name: 'Attack',
            matchClue: 'How quickly the compressor begins acting once the signal crosses the set level.',
            description: 'Controls how quickly the compressor reacts once the signal exceeds the {{B}} threshold. A fast attack (< 5 ms) catches transients immediately, reducing punchiness. A slow attack (> 20 ms) lets the initial transient through before compressing, preserving the natural attack of drums or plucked instruments. Works closely with {{E}} release to shape the compression envelope.',
            questions: [
                { q: 'Should I use a fast or slow attack on drums?', a: 'It depends on what you want. A slow attack (20-30 ms) lets the initial hit of the drum through uncompressed, preserving punch and snap. A fast attack (< 5 ms) catches that transient and softens it, which can make drums sound thicker but less punchy. For most drum mixing, a slower attack is preferred.' },
                { q: 'What does attack time actually measure?', a: 'Attack time is how long the compressor takes to reach full compression after the signal crosses the {{B}} threshold. At 1 ms, compression kicks in almost instantly. At 30 ms, the first 30 milliseconds of audio above the threshold pass through before the compressor fully engages.' },
                { q: 'Can attack time change the tone of a sound?', a: 'Yes, significantly. Attack is one of the most powerful tone-shaping tools on a compressor. A fast attack dulls transients and can make a sound feel smoother or darker. A slow attack emphasises transients, adding perceived brightness and aggression. This is why engineers often reach for the attack knob first.' },
            ],
        },
        {
            id: 'release',
            label: 'E',
            zone: { left: 57, width: 13 },
            color: '#9B7530',
            level: 'foundation',
            name: 'Release',
            matchClue: 'How quickly the compressor stops acting after the signal drops back below the set level.',
            description: 'Sets how quickly the compressor stops compressing after the signal falls below the {{B}} threshold. Too fast a release can cause audible "pumping" or "breathing" artefacts. Too slow a release can squash the dynamics of the next note or beat. Typical values range from 50 ms to 500 ms.',
            questions: [
                { q: 'What does "pumping" sound like and how do I avoid it?', a: 'Pumping is a rhythmic swelling effect where the volume audibly rises and falls as the compressor engages and releases. It sounds like the track is "breathing." It happens when the release is too fast — the compressor lets go between beats, causing noticeable volume jumps. Slow the release down until the compression feels smooth and even.' },
                { q: 'How do release and attack work together?', a: '{{D}} Attack controls how quickly compression starts; release controls how quickly it stops. Together they shape the "envelope" of the compression. A fast attack + slow release = sustained, even compression. A slow attack + fast release = transients punch through but the compressor recovers quickly for the next hit. The combination is what gives compression its character.' },
                { q: 'When would I deliberately use a fast release?', a: 'A fast release can be creative. On a drum bus, a fast release creates an aggressive, punchy sound where the compressor clamps down then snaps back, making the room tone or reverb tail swell up between hits. This is the classic "rock drums" compression sound — often combined with {{A}} sidechain from the kick. Just be aware it can cause distortion on sustained bass notes.' },
            ],
        },
        {
            id: 'knee',
            label: 'F',
            zone: { left: 71, width: 13 },
            color: '#B85A3F',
            level: 'advanced',
            name: 'Knee',
            matchClue: 'Controls whether the transition into compression is abrupt or gradual.',
            description: 'Controls how gradually compression is applied around the {{B}} threshold. A hard knee (0 dB) applies the full {{C}} ratio abruptly as soon as the signal crosses the threshold. A soft knee applies compression gradually, starting slightly below the threshold and reaching the full ratio above it. Soft knee sounds more transparent and natural.',
            questions: [
                { q: 'When should I use a soft knee vs hard knee?', a: 'Use a soft knee when you want transparent, unnoticeable compression — vocals, acoustic instruments, mastering. The gradual onset makes the compression feel natural. Use a hard knee when you want obvious, characterful compression — parallel drum compression, aggressive bass, or any time you want to hear the compressor working as an effect.' },
                { q: 'Does knee affect how much compression is applied?', a: 'Not the total amount — that is still determined by {{B}} threshold and {{C}} ratio. Knee only affects the transition zone around the threshold. With a soft knee, compression begins gently a few dB below the threshold and reaches the full ratio a few dB above it. The result is the same amount of compression on loud signals, but a smoother transition getting there.' },
            ],
        },
        {
            id: 'makeup-gain',
            label: 'G',
            zone: { left: 85, width: 15 },
            color: '#0891B2',
            level: 'advanced',
            name: 'Makeup Gain',
            matchClue: 'Restores the overall volume after the dynamic range has been reduced.',
            description: 'Boosts the output level to compensate for the volume reduction caused by compression. The more you compress — controlled by the {{B}} threshold and {{C}} ratio — the more makeup gain you will typically need. Makeup gain restores the perceived loudness while keeping the tighter dynamic range that compression provides.',
            questions: [
                { q: 'How much makeup gain should I add?', a: 'Match the output level to the input level. The easiest way: bypass the compressor on and off and adjust makeup gain until the volume sounds the same in both states. This lets you hear the tonal and dynamic changes of the compression without being fooled by the volume difference. Louder always sounds "better" to our ears, which can trick you into thinking bad settings sound good.' },
                { q: 'Why does compression make things quieter?', a: 'Compression reduces the level of signals above the {{B}} threshold. If your loudest peaks were at 0 dB and the compressor reduces them by 6 dB, the peaks are now at -6 dB. The quiet parts haven\'t changed, but the overall signal is quieter because the peaks have been pulled down. Makeup gain brings everything back up, so the quiet parts are now louder relative to where the peaks used to be — that\'s how compression increases perceived loudness.' },
                { q: 'What is the difference between makeup gain and output gain?', a: 'In most compressors they are the same thing — a volume boost applied after compression. Some compressors label it "output" or "gain" instead of "makeup." The function is identical: compensate for the volume lost during compression. Some compressors offer an "auto makeup gain" feature that estimates the right amount automatically.' },
            ],
        },
    ],
};

export default compressorConfig;
