const delayConfig = {
    imageSrc: '/images/explorers/ableton-delay.png',
    imageAlt: 'Ableton Live Delay effect interface showing delay time, sync, feedback, filter and dry/wet controls',
    title: 'Delay Controls Explorer',
    instruction: 'Drag a cable from the floating box to a coloured zone below the image to learn what that control does.',
    hotspots: [
        {
            id: 'delay-time',
            label: 'A',
            zone: { left: 0, width: 20 },
            anchor: { x: 10, y: 32 },
            color: '#E8590C',
            level: 'foundation',
            name: 'Delay Time',
            matchClue: 'How long the gap is between the original sound and the delayed repeat.',
            description: 'Sets the time between the original signal and each repeated echo. In Sync mode, this is set in musical note values (1/4, 1/8, 1/16 etc.) that lock to the project tempo. In free-running mode, it is set in milliseconds. Short delay times (1-30 ms) create doubling and chorus-like effects. Medium times (30-100 ms) create slapback echo. Longer times (100 ms+) create distinct rhythmic echoes.',
            questions: [
                { q: 'What is the difference between synced and free-running delay?', a: 'Synced delay locks the repeat time to the project tempo using note values: a 1/8 note delay at 120 BPM always repeats every 250 ms, and adjusts automatically if the tempo changes. Free-running delay is set in milliseconds and stays fixed regardless of tempo. Use synced delay for rhythmic, musical echoes. Use free-running for sound design, slapback, or when tempo-locking is not needed.' },
                { q: 'What delay times create common effects?', a: '1-10 ms: Comb filtering and phasing effects (too short to hear as separate echoes). 10-30 ms: Doubling: sounds like two performances layered together. 30-100 ms: Slapback echo: the classic rockabilly/Elvis vocal effect. 100-250 ms: Rhythmic echoes that fill gaps between words or notes. 250-500 ms+: Distinct repeats that create call-and-response patterns. Each range has a completely different character.' },
                { q: 'Can I set different delay times for left and right?', a: 'Yes. Many delays including Ableton\'s allow independent left and right delay times. Setting different times for each side creates a wide stereo effect where echoes ping between the speakers at different rates. For example, 1/8 note on the left and dotted 1/8 on the right creates a classic stereo delay pattern used on guitars and vocals. This is related to the {{E}} ping pong mode.' },
            ],
        },
        {
            id: 'sync',
            label: 'B',
            zone: { left: 20, width: 14 },
            anchor: { x: 16, y: 50 },
            color: '#D97706',
            level: 'foundation',
            name: 'Sync Mode',
            matchClue: 'Locks the delay time to the project tempo using musical note values.',
            description: 'When Sync is enabled, the {{A}} delay time is expressed in musical note values (1/4, 1/8, 1/16, dotted, triplet) that automatically follow the project tempo. This ensures the echoes always fall on rhythmically meaningful positions in the bar. When Sync is off, the delay time is set in milliseconds and does not follow tempo changes.',
            questions: [
                { q: 'What are the most common synced delay times?', a: '1/4 note: echoes on every beat, dramatic, obvious. 1/8 note: echoes on every eighth note: the most common mixing delay for filling gaps. Dotted 1/8: creates a rhythmic "galloping" pattern that falls between beats: the classic U2/Edge guitar delay. 1/16 note: fast, subtle echoes that add thickness and space. Triplet values: create a swing or shuffle feel to the echoes.' },
                { q: 'What is a dotted note delay?', a: 'A dotted note is 1.5 times the length of a regular note. A dotted 1/8 note is the length of an eighth note plus a sixteenth note. This means the echo falls between the straight beat divisions, creating an off-beat, syncopated rhythm. It is one of the most musically interesting delay settings because the repeats interlock with the original rhythm rather than landing directly on beats.' },
                { q: 'When should I use free-running (unsynced) delay?', a: 'Free-running delay is useful for slapback effects (a single short echo around 80-120 ms that does not need to be rhythmic), sound design where you want echoes that drift independently of the beat, and when processing audio that has no fixed tempo. It is also used for very short delays (under 30 ms) that create doubling or chorus effects.' },
            ],
        },
        {
            id: 'feedback',
            label: 'C',
            zone: { left: 34, width: 18 },
            anchor: { x: 23, y: 85 },
            color: '#059669',
            level: 'foundation',
            name: 'Feedback',
            matchClue: 'Controls how many times the echo repeats by feeding the output back into the input.',
            description: 'Feedback routes the delayed signal back into the delay input, creating multiple repeating echoes. At 0%, you hear a single echo. As feedback increases, more repeats are generated, each one quieter than the last. At very high feedback (above 90%), the repeats barely decay and can build up indefinitely: use with caution. The {{D}} filter affects the tone of each successive repeat, so with feedback and filtering, each echo gets progressively darker or thinner.',
            questions: [
                { q: 'How does feedback affect the number of repeats?', a: 'Low feedback (10-30%): 2-4 subtle repeats that fade quickly: good for adding depth without clutter. Medium feedback (30-60%): 5-10 repeats that create a rhythmic trail: the most common mixing range. High feedback (60-85%): many repeats that sustain for a long time: creates a wash of echoes, good for ambient and atmospheric effects. Above 90%: dangerous territory: repeats barely decay and can build up to infinite, runaway feedback.' },
                { q: 'What happens if feedback is too high?', a: 'At very high feedback levels, each repeat is almost as loud as the one before it. The echoes accumulate rather than fading, and the signal can build up until it distorts or becomes an overwhelming wall of sound. This is called runaway feedback. Some delays have a safety limiter, but many do not. It can be a creative tool for dramatic builds, but always be ready to pull the feedback down quickly.' },
                { q: 'How do feedback and the filter interact?', a: 'When the {{D}} filter is active, each repeat passes through the filter again. With a low-pass filter, each successive echo loses more high frequency content: the echoes gradually darken and recede, mimicking how sound loses brightness over distance in a real space. This combination of feedback and filtering is one of the most powerful creative tools on a delay: it creates organic, evolving echo tails.' },
            ],
        },
        {
            id: 'filter',
            label: 'D',
            zone: { left: 52, width: 16 },
            anchor: { x: 55, y: 90 },
            color: '#2563EB',
            level: 'advanced',
            name: 'Filter',
            matchClue: 'Shapes the tone of the delayed signal, making each repeat progressively brighter or darker.',
            description: 'The delay filter processes the wet signal, shaping the tone of the echoes independently from the dry sound. A low-pass filter removes high frequencies from the repeats, making each echo progressively warmer and darker: mimicking the natural absorption of treble in a real space. A high-pass filter thins out the repeats. With {{C}} feedback active, the filter is applied to each successive repeat, creating a cumulative tonal shift across the echo tail.',
            questions: [
                { q: 'Why would I filter the delay signal?', a: 'Unfiltered digital delay can sound harsh and clinical: the repeats are identical copies of the original, which rarely sounds natural. In the real world, echoes lose high frequency content as sound travels through air and bounces off surfaces. Adding a gentle low-pass filter (around 4-8 kHz) makes the delay sound warmer, more natural, and less obtrusive in a mix. It also prevents the echoes from competing with the brightness of the dry signal.' },
                { q: 'How does filtering create an analogue delay sound?', a: 'Classic analogue tape delays and bucket-brigade delays naturally lost high frequencies with each repeat due to the limitations of their technology. Each echo was progressively darker and slightly degraded. The filter on a digital delay recreates this characteristic. Set a low-pass filter around 3-5 kHz with moderate {{C}} feedback and you get a warm, vintage echo that sits beautifully behind the dry signal without drawing attention to itself.' },
                { q: 'When would I use a high-pass filter on the delay?', a: 'A high-pass filter on the delay removes bass from the repeats, which is useful for preventing low-frequency buildup when using delay on bass-heavy instruments. It keeps the echoes thin and airy rather than boomy. This is also effective when you want the delay to add rhythmic interest and space in the upper frequencies without adding muddiness to the low end of your mix.' },
            ],
        },
        {
            id: 'ping-pong',
            label: 'E',
            zone: { left: 68, width: 14 },
            anchor: { x: 84, y: 85 },
            color: '#9B7530',
            level: 'advanced',
            name: 'Stereo / Ping Pong',
            matchClue: 'Alternates the echoes between the left and right speakers, creating a bouncing stereo effect.',
            description: 'Ping pong mode alternates each repeat between the left and right stereo channels, creating echoes that bounce between speakers. The first repeat goes to one side, the next to the other, and so on. This creates a wide, spatial effect that adds excitement and movement. It is particularly effective on vocals, guitars, and synths where you want the delay to fill the stereo field without cluttering the centre of the mix.',
            questions: [
                { q: 'When should I use ping pong versus regular stereo delay?', a: 'Use ping pong when you want dramatic, obvious stereo movement. The bouncing echoes are attention-grabbing and work well in sparse mixes, breakdowns, or on lead elements. Use regular stereo delay (independent left/right {{A}} times) for subtler width that does not draw attention. In a dense mix, ping pong can be distracting; in a minimal arrangement, it adds exciting motion.' },
                { q: 'Does ping pong delay work in mono?', a: 'When summed to mono (as happens on phone speakers, some PA systems, or mono-compatible broadcast), the left and right echoes collapse to the centre and play simultaneously. This can cause comb filtering or a different rhythmic feel than intended. Always check your ping pong delay in mono: if it sounds bad, consider using a shorter {{A}} delay time or reducing the {{C}} feedback to minimise the issue.' },
                { q: 'How can I make ping pong delay sit better in a mix?', a: 'Use the {{D}} filter to darken the repeats so they sit behind the dry signal. Keep the {{C}} feedback moderate (30-50%) so the bouncing does not become overwhelming. Consider using a longer {{A}} delay time (1/4 or dotted 1/8) rather than very fast repeats. And use the {{F}} dry/wet to blend the effect tastefully: a little ping pong goes a long way.' },
            ],
        },
        {
            id: 'dry-wet',
            label: 'F',
            zone: { left: 82, width: 18 },
            anchor: { x: 94, y: 82 },
            color: '#B85A3F',
            level: 'foundation',
            name: 'Dry/Wet',
            matchClue: 'The balance between the original unprocessed signal and the delayed echoes.',
            description: 'Controls the mix between the dry (original) signal and the wet (delayed) signal. At 0%, no delay is heard. At 100%, only the delayed signal is heard. Like reverb, delay is typically used on a send/return channel at 100% wet, with send levels controlling how much delay each track gets. When used as an insert, 15-35% wet is a common range for mixing: enough to hear the effect without the echoes overpowering the source.',
            questions: [
                { q: 'How is using delay on a send different from an insert?', a: 'On a send/return, the delay is set to 100% wet and multiple tracks can share the same delay, each with different send amounts. This is the professional standard because it is more efficient and allows you to process the delay return independently (EQ, compression, further effects). On an insert, the delay processes only that track and you blend with Dry/Wet.' },
                { q: 'How much delay should I use in a mix?', a: 'Start with the Dry/Wet at 0% and gradually increase until the echoes fill the gaps between phrases or notes without drawing attention to themselves. The delay should support the source rather than dominate it. If the echoes are obvious and distracting, reduce the wet level. A well-mixed delay is often felt more than heard. It adds depth and rhythm without the listener consciously noticing it.' },
                { q: 'What is the difference between using delay and reverb for depth?', a: 'Delay creates discrete echoes at specific time intervals: it adds rhythmic interest and can widen the stereo image. Reverb creates a continuous wash of reflections: it simulates a physical space and adds a sense of environment. In practice, engineers often use both together: a short delay for rhythmic interest and width, plus reverb for space and depth. Each serves a different purpose.' },
            ],
        },
    ],
};

export default delayConfig;
