const eq8Config = {
    imageSrc: '/images/explorers/ableton-eq8.png',
    imageAlt: 'Ableton Live EQ Eight effect interface showing eight filter bands with frequency, gain and Q controls',
    title: 'EQ Eight Controls Explorer',
    instruction: 'Drag a cable from the floating box to a coloured zone below the image to learn what that control does.',
    daw: 'Ableton Live',
    dawNote: 'Every DAW has a parametric EQ; this one is Ableton Live\'s EQ Eight. The concepts (frequency, gain, Q) are the same wherever you find them.',
    hotspots: [
        {
            id: 'band-selectors',
            label: 'A',
            zone: { left: 0, width: 25 },
            color: '#E8590C',
            level: 'foundation',
            name: 'Band Selectors',
            matchClue: 'The numbered buttons at the bottom that enable or disable individual EQ bands.',
            description: 'EQ Eight provides eight independent filter bands, numbered 1 to 8. Each band can be enabled or disabled by clicking its numbered button at the bottom of the interface. Each band has its own {{B}} frequency, {{C}} gain, and {{D}} Q settings. When you select a band, its coloured dot appears on the frequency display and you can adjust its parameters. You can combine multiple bands to shape the sound: for example, using band 1 as a low cut, bands 3-4 for corrective cuts, and band 8 as a high shelf.',
            questions: [
                { q: 'Do I need to use all eight bands?', a: 'No. Only enable the bands you need. Most mixing tasks require 3-5 bands: a high-pass to remove rumble, one or two cuts to remove problem frequencies, and perhaps a shelf boost for presence or air. Enable more only when the material genuinely needs it. Every active band processes the audio, so unnecessary bands add processing for no benefit.' },
                { q: 'What types of filter shape can each band be?', a: 'Each band can be set to a different filter shape. The most common are: bell (boosts or cuts a range centred on a frequency), low-cut/high-pass (removes everything below a frequency), high-cut/low-pass (removes everything above), low shelf (boosts or cuts everything below), high shelf (boosts or cuts everything above), and notch (cuts a very narrow band). The shape icons appear next to the band number.' },
                { q: 'Can I drag the dots on the display directly?', a: 'Yes. Each enabled band appears as a coloured dot on the frequency response display. You can click and drag these dots: horizontal movement changes the {{B}} frequency, vertical movement changes the {{C}} gain. This gives you a visual, intuitive way to shape the EQ curve. The knob values below update to match your drag position.' },
            ],
        },
        {
            id: 'frequency',
            label: 'B',
            zone: { left: 25, width: 25 },
            color: '#D97706',
            level: 'foundation',
            name: 'Frequency',
            matchClue: 'The centre or cutoff frequency for the selected band: shown on the x-axis (horizontal) of the display.',
            description: 'Sets the target frequency for the selected band. On the display, frequency is shown on the x-axis (horizontal): low frequencies on the left, high frequencies on the right. The scale is logarithmic, meaning each octave takes up the same amount of space. For bell shapes, this sets the centre of the boost or cut. For shelves, it is the transition point. For cuts, it is the cutoff point where the filter begins removing frequencies.',
            questions: [
                { q: 'Why is the x-axis logarithmic rather than linear?', a: 'Human hearing perceives pitch logarithmically: the distance between 100 Hz and 200 Hz sounds the same as 1 kHz to 2 kHz (both are one octave). A logarithmic scale matches how we actually hear, so equal distances on the display represent equal musical intervals. If it were linear, the entire bass range would be squashed into a tiny space on the left.' },
                { q: 'How do I find a problem frequency?', a: 'A common technique: temporarily set a narrow {{D}} Q and a large {{C}} gain boost (around +10 dB), then slowly sweep the frequency across the spectrum. Problem frequencies will jump out as unpleasant resonances or harshness. Once found, reduce the gain to cut that frequency. This "boost and sweep" technique helps your ears locate issues quickly.' },
                { q: 'What frequency ranges are important for mixing?', a: 'Sub-bass (20-60 Hz): rumble, felt more than heard. Bass (60-250 Hz): warmth and body. Low-mids (250-500 Hz): muddiness often lives here. Mids (500 Hz-2 kHz): body and presence of most instruments. Upper-mids (2-5 kHz): clarity, definition, and vocal intelligibility. Presence (5-8 kHz): brightness and air. Highs (8-20 kHz): sparkle and sizzle.' },
            ],
        },
        {
            id: 'gain',
            label: 'C',
            zone: { left: 50, width: 25 },
            color: '#059669',
            level: 'foundation',
            name: 'Gain',
            matchClue: 'How much the selected frequency is boosted or cut: shown on the y-axis (vertical) of the display.',
            description: 'Controls the amount of boost (positive dB) or cut (negative dB) applied at the {{B}} frequency. On the display, gain is shown on the y-axis (vertical). The centre line is 0 dB (no change), above is boost, below is cut. The curve drawn on the display shows the combined effect of all active bands. In general, cutting (subtractive EQ) is preferred over boosting: removing a problem frequency is usually more effective and sounds more natural than trying to boost what you want.',
            questions: [
                { q: 'Why is cutting preferred over boosting?', a: 'Cutting removes problematic frequencies, revealing what is already good in the recording. Boosting adds energy and can introduce noise, phase issues, or harshness. "Subtractive EQ" tends to sound more natural. For example, instead of boosting 3 kHz for vocal presence, try cutting 300-500 Hz to remove muddiness: the presence emerges naturally without adding any extra energy.' },
                { q: 'How much boost or cut is too much?', a: 'As a guideline, if you need more than 6 dB of boost, consider whether the issue should be fixed at the source: microphone choice, placement, or performance. Cuts can be more aggressive: a narrow 12 dB cut to remove a resonance is perfectly reasonable. But broad boosts above 6 dB usually indicate a recording problem rather than a mixing solution.' },
                { q: 'What does the curve on the display show me?', a: 'The white curve shows the combined frequency response of all your active bands. Where the curve is above the centre line, those frequencies are being boosted. Where it dips below, they are being cut. The shape of the curve tells you exactly what your EQ is doing to the signal across the entire frequency spectrum. A flat line means no change.' },
            ],
        },
        {
            id: 'q-bandwidth',
            label: 'D',
            zone: { left: 75, width: 25 },
            color: '#2563EB',
            level: 'foundation',
            name: 'Q (Bandwidth)',
            matchClue: 'How wide or narrow the affected frequency range is around the centre frequency.',
            description: 'Q determines the bandwidth: how many frequencies around the {{B}} centre frequency are affected by the {{C}} gain change. A low Q (wide bandwidth) affects a broad range of frequencies, creating gentle, musical tone shaping. A high Q (narrow bandwidth) focuses on a tight range, useful for surgical corrections like removing a ringing frequency. On the display, you can see the width of the curve change as you adjust Q.',
            questions: [
                { q: 'What Q value should I use for general tone shaping?', a: 'For broad, musical tone shaping (making a vocal brighter, warming up a guitar), use a low Q around 0.5-1.5. This affects a wide range of frequencies gently, which sounds natural. For removing specific problem frequencies (a ringing tom, a harsh resonance, a 50 Hz hum), use a higher Q of 4-10 to target just that frequency without affecting the surrounding area.' },
                { q: 'What does Q stand for?', a: 'Q stands for "quality factor": a term from electronics that describes the selectivity of a resonant circuit. In audio, higher Q means a more selective (narrower) filter. A Q of 1 is considered moderate bandwidth. Below 1 is wide, above 4 is narrow. It is the inverse of bandwidth: high Q = narrow bandwidth, low Q = wide bandwidth.' },
                { q: 'How can I see the effect of Q on the display?', a: 'Select a band with some {{C}} gain boost, then adjust Q. With a low Q you will see a wide, gentle hill on the frequency response curve. As you increase Q, the hill becomes a tall, narrow peak. The same works for cuts: low Q gives a gentle dip, high Q gives a narrow notch. The display gives you instant visual feedback on how much of the spectrum you are affecting.' },
            ],
        },
    ],
};

export default eq8Config;
