const gateConfig = {
    imageSrc: '/images/explorers/ableton-gate.png',
    imageAlt: 'Ableton Live Gate effect interface showing threshold, return, attack, hold, release, floor, and sidechain controls',
    title: 'Gate Controls Explorer',
    instruction: 'Drag a cable from the floating box to a coloured zone below the image to learn what that control does.',
    daw: 'Ableton Live',
    dawNote: 'Every DAW has a noise gate; this one is Ableton Live\'s Gate device. The concepts — threshold, hold, release, floor — are the same wherever you find them.',
    hotspots: [
        {
            id: 'sidechain',
            label: 'A',
            zone: { left: 0, width: 13 },
            color: '#E8590C',
            level: 'advanced',
            name: 'Sidechain',
            matchClue: 'Routes a separate audio source to trigger the gate, rather than the signal being processed itself.',
            description: 'Enables sidechain gating, where the gate listens to an external signal (the "key" or "trigger") instead of the signal it is processing. For example, a hi-hat pattern can trigger a gate on a synth pad, creating a rhythmic chopping effect. The {{C}} threshold still controls when the gate opens — sidechain only changes what signal is being monitored.',
            questions: [
                { q: 'When would I use sidechain gating?', a: 'Sidechain gating is commonly used to create rhythmic effects — routing a drum pattern to trigger a gate on a pad or vocal creates a choppy, rhythmic texture. It is also used in live sound to gate a snare mic using the snare itself as the trigger from a cleaner source, reducing bleed from other drums.' },
                { q: 'How is sidechain gating different from sidechain compression?', a: 'With sidechain compression, the external signal controls how much the volume is reduced — it ducks the audio. With sidechain gating, the external signal controls whether the audio passes through at all. The gate is either open or closed (or partially closed, depending on the {{G}} floor), making the effect much more dramatic.' },
                { q: 'What signal should I route to the sidechain input?', a: 'Route whichever signal you want to use as the trigger. For rhythmic chopping, use a drum loop or click track. For cleaning up drum bleed, use the close-mic of the drum you want to isolate. In Ableton, set the "Sidechain" source dropdown to the track you want to trigger from.' },
            ],
        },
        {
            id: 'return',
            label: 'B',
            zone: { left: 14, width: 13 },
            color: '#D97706',
            level: 'advanced',
            name: 'Return',
            matchClue: 'The level below the threshold at which the gate closes again, preventing rapid on-off switching.',
            description: 'Also called hysteresis, this sets how far below the {{C}} threshold the signal must drop before the gate closes. For example, if the threshold is -20 dB and return is set to -3 dB, the gate opens at -20 dB but will not close again until the signal drops below -23 dB. This prevents the gate from rapidly opening and closing (chattering) when the signal hovers around the threshold.',
            questions: [
                { q: 'What is gate chatter and how does return prevent it?', a: 'Gate chatter happens when a signal hovers right at the {{C}} threshold level — the gate rapidly opens and closes, creating an unpleasant stuttering or buzzing sound. Return creates a gap between the opening and closing levels. The signal must drop further below the threshold before the gate closes, so small level fluctuations near the threshold do not cause rapid switching.' },
                { q: 'What is a good starting value for return?', a: 'A return of -3 dB to -6 dB below the threshold works well in most situations. If you hear chattering, increase the return value. If the gate is staying open too long and letting through unwanted noise at the end of a sound, reduce it. The goal is a smooth, natural gate action without audible switching artefacts.' },
            ],
        },
        {
            id: 'threshold',
            label: 'C',
            zone: { left: 28, width: 13 },
            color: '#059669',
            level: 'foundation',
            name: 'Threshold',
            matchClue: 'The level above which the gate opens to let the signal through.',
            description: 'Sets the level (in dB) that the signal must exceed for the gate to open. When the signal is above this level, audio passes through. When it drops below, the gate closes and the signal is attenuated down to the {{G}} floor level. The {{B}} return control adds hysteresis so the gate does not chatter at the threshold boundary.',
            questions: [
                { q: 'What happens if I set the threshold too high?', a: 'If the threshold is too high, the gate will cut off parts of the signal you want to keep. Quiet notes, the tails of drum hits, or softer vocal phrases may be silenced because they do not reach the threshold. You will hear unnatural, choppy cutoffs.' },
                { q: 'What happens if I set the threshold too low?', a: 'If the threshold is too low, the gate stays open most of the time, allowing bleed and noise through — defeating the purpose. The gate only closes during the very quietest moments. You want the threshold just above the level of the unwanted noise but below the level of the signal you want to keep.' },
                { q: 'How do I find the right threshold?', a: 'Play back the audio and watch the input meter. Identify the level of the noise or bleed you want to remove, and set the threshold just above that. Then listen carefully to make sure the gate opens fully for the wanted signal without cutting off any tails or quiet passages. Adjust the {{B}} return if the gate is chattering.' },
            ],
        },
        {
            id: 'attack',
            label: 'D',
            zone: { left: 42, width: 13 },
            color: '#2563EB',
            level: 'foundation',
            name: 'Attack',
            matchClue: 'How quickly the gate opens once the signal exceeds the threshold.',
            description: 'Controls how quickly the gate opens when the signal crosses the {{C}} threshold. A fast attack (< 1 ms) opens the gate almost instantly, preserving sharp transients like drum hits. A slower attack softens the onset of the sound, which can create fade-in effects or smooth out harsh transients.',
            questions: [
                { q: 'Should I always use a fast attack on a gate?', a: 'For drums and percussive sounds, yes — a fast attack (0.01-0.5 ms) ensures the initial transient is not lost. But for vocals or sustained instruments, a slightly slower attack (1-5 ms) can sound more natural and avoid clicks. An extremely fast attack can sometimes produce an audible click as the gate snaps open.' },
                { q: 'Can a gate click when it opens?', a: 'Yes. If the attack is extremely fast and the signal is already at a high level when the gate opens, the sudden jump from silence (or the {{G}} floor level) to the full signal can create an audible click. A slightly slower attack or raising the {{G}} floor can help eliminate this artefact.' },
                { q: 'How does gate attack differ from compressor attack?', a: 'A compressor attack controls how quickly gain reduction begins — it is about reducing volume. A gate attack controls how quickly the gate opens to let signal through — it is about allowing volume. They are opposite actions: compression reacts to loud signals by turning down; gating reacts to loud signals by turning up (opening).' },
            ],
        },
        {
            id: 'hold',
            label: 'E',
            zone: { left: 56, width: 13 },
            color: '#9B7530',
            level: 'foundation',
            name: 'Hold',
            matchClue: 'The minimum time the gate stays open after the signal drops below the threshold.',
            description: 'Sets the minimum time the gate remains open after the signal falls below the {{C}} threshold, before the {{F}} release phase begins. This prevents the gate from closing prematurely on signals with natural volume dips, like a drummer hitting slightly softer mid-phrase. Hold ensures a consistent minimum open time regardless of signal level.',
            questions: [
                { q: 'Why do I need hold if I have release?', a: 'Hold and {{F}} release do different things. Hold keeps the gate fully open for a set time after the signal drops below the threshold — the signal passes through at full volume. Release then controls how quickly the gate fades closed after the hold time expires. Without hold, the release would start immediately, and short dips in level could trigger premature closing.' },
                { q: 'What is a good hold time for drums?', a: 'For snare drums, 20-50 ms works well — long enough to capture the full body of the hit without cutting it short. For kick drums, 30-80 ms. For toms, 50-150 ms depending on how much ring you want to keep. Listen for the natural decay of the drum and set hold to capture at least the body of the sound.' },
                { q: 'When would I use a very long hold time?', a: 'A long hold time (200+ ms) is useful when gating vocals or sustained instruments where natural phrasing has brief quiet moments. It keeps the gate open through short pauses so the gate does not cut mid-phrase. Combined with a longer {{F}} release, this creates smooth, natural-sounding gating.' },
            ],
        },
        {
            id: 'release',
            label: 'F',
            zone: { left: 70, width: 14 },
            color: '#B85A3F',
            level: 'foundation',
            name: 'Release',
            matchClue: 'How quickly the gate closes after the hold time has expired.',
            description: 'Controls how quickly the gate fades from fully open down to the {{G}} floor level, after the {{E}} hold time has expired. A fast release cuts the signal off sharply, which can sound unnatural. A slower release creates a gradual fade-out that sounds more natural, especially on drums with resonant tails or sustained instruments.',
            questions: [
                { q: 'What happens if the release is too fast?', a: 'A very fast release cuts the sound off abruptly, which can sound unnatural — like someone hitting a mute button. On drums, it removes the natural decay and room ambience. On vocals, it chops off word endings. You may also hear a click if the waveform is cut at a non-zero crossing point.' },
                { q: 'What happens if the release is too slow?', a: 'A very slow release means the gate takes a long time to close, so noise and bleed continue to come through during the fade-out. This reduces the effectiveness of the gate — you wanted to remove that noise, but a slow release lets it linger. Find the balance between natural-sounding decay and effective noise removal.' },
                { q: 'How do hold and release work together for drums?', a: 'For a snare drum: set {{E}} hold to around 30-50 ms to capture the body of the hit, then set release to 50-100 ms so the tail fades out naturally rather than being cut off. The hold keeps the gate fully open for the initial hit, then the release creates a smooth fade. Without hold, the release would start too early and thin out the sound.' },
            ],
        },
        {
            id: 'floor',
            label: 'G',
            zone: { left: 85, width: 15 },
            color: '#0891B2',
            level: 'foundation',
            name: 'Floor',
            matchClue: 'The amount of attenuation applied when the gate is closed — how quiet the signal gets.',
            description: 'Sets the level the signal is reduced to when the gate is closed. At -inf dB (fully closed), the gate completely silences the signal. At higher floor values like -12 dB or -6 dB, some signal still passes through even when the gate is closed, which sounds more natural and avoids the "dead silence" effect between notes.',
            questions: [
                { q: 'Why would I not set the floor to -inf (complete silence)?', a: 'Complete silence between notes or drum hits can sound unnatural — it removes all room ambience and background, creating an obvious "gate is on" effect. Setting the floor to -20 dB or -12 dB allows some room tone and bleed through when the gate is closed, which sounds more natural while still significantly reducing noise. This is especially important for live recordings where the room sound is part of the character.' },
                { q: 'What floor setting should I use for drums?', a: 'For close-miked drums in a studio, -inf works well because there is less room sound to preserve. For live recordings or overhead mics, try -20 to -12 dB so some room ambience remains. For extreme gated drum effects (like 80s gated reverb), use -inf for the dramatic cut-off. Always compare gated and ungated to check it sounds natural.' },
                { q: 'How is floor different from a noise gate that just mutes?', a: 'A simple noise gate is either open or closed — binary on/off. The floor control turns a gate into an expander by allowing partial attenuation. Instead of muting completely, it reduces the signal by a set amount. This gives you much more control and sounds far more natural. Many engineers prefer a -20 dB floor over complete silence for this reason.' },
            ],
        },
    ],

    // ── WO-10: the Logic Pro counterpart (Mike's decision 5, 2026-08-12). ──
    // Screenshot verified 2026-08-12: Gate/Ducker tabs, Threshold, Reduction,
    // Hysteresis, Attack/Hold/Release, Lookahead, Open/Close monitor.
    // Teaching content anchored on the lab effects rack's Mike-verified
    // entries (studio-lab app/effects/data.js → gate.logic) and the shared
    // gate concepts above — where a control exists in one DAW but not the
    // other, the copy names the difference rather than pretending the
    // devices are identical.
    logic: {
        imageSrc: '/images/explorers/logic-noise-gate.png',
        imageAlt: 'Logic Pro Noise Gate interface showing Gate and Ducker tabs, threshold, reduction, hysteresis, attack, hold, release and lookahead controls',
        daw: 'Logic Pro',
        dawNote: 'Logic’s Noise Gate does the same job as Ableton’s Gate with three renames worth knowing: Ableton’s Return is Logic’s Hysteresis, Ableton’s Floor is Logic’s Reduction, and Logic adds Lookahead plus a whole Ducker mode. The Open/Close lamps at the top right simply show whether the gate is currently passing signal.',
        hotspots: [
            {
                id: 'gate-ducker',
                label: 'A',
                zone: { left: 0, width: 11 },
                color: '#E8590C',
                level: 'advanced',
                name: 'Gate / Ducker tabs',
                matchClue: 'Switches the device between removing quiet material and automatically dipping a signal when another plays.',
                description: 'In Gate mode the device silences signal below the {{B}} threshold — the standard noise-gate job. Ducker mode inverts the logic: the signal is turned DOWN while the sidechain input is loud, the classic radio-DJ effect where music dips under a voice. Ableton’s Gate has no Ducker mode — in Ableton, ducking is normally built with sidechain compression instead.',
                questions: [
                    { q: 'What is ducking used for?', a: 'Ducking automatically lowers one signal while another plays — music dipping under a voiceover, a pad making room for a lead vocal, or a delay return ducking while the dry vocal sings so the repeats only bloom in the gaps. In Logic you can do this directly from the Noise Gate’s Ducker mode with a sidechain input.' },
                    { q: 'How would I make the same ducking effect in Ableton Live?', a: 'Ableton’s Gate has no Ducker mode, so you would use a Compressor with its sidechain input instead: the compressor on the music listens to the voice, and turns the music down whenever the voice is present. Same musical result, different tool — worth naming the route for whichever DAW the question shows you.' },
                ],
            },
            {
                id: 'threshold',
                label: 'B',
                zone: { left: 12, width: 11 },
                color: '#059669',
                level: 'foundation',
                name: 'Threshold',
                matchClue: 'The level the signal must exceed for the gate to open.',
                description: 'Sets the level (in dB) the signal must exceed for the gate to open — identical in concept to Ableton’s threshold. Above it, audio passes; below it, the signal is turned down by the {{C}} reduction amount. Set it just above the noise or bleed you want to remove, and use {{D}} hysteresis to stop the gate stuttering when the signal hovers near the line.',
                questions: [
                    { q: 'How do I find the right threshold?', a: 'Play the audio and watch the level meters. Identify the level of the noise or bleed you want removed, and set the threshold just above it. Then listen carefully to the material you want to KEEP — if quiet notes or drum tails are being cut off, the threshold is too high. The green arc around Logic’s Threshold knob shows the range at a glance.' },
                    { q: 'What goes wrong if the threshold is too high or too low?', a: 'Too high, and wanted material gets silenced — note tails and ghost notes vanish, sounding choppy and unnatural. Too low, and the gate barely closes, letting the noise through and defeating the point. The threshold sits in the gap between the noise level and the wanted signal level; if there is no such gap, a gate alone cannot fix the recording.' },
                ],
            },
            {
                id: 'reduction',
                label: 'C',
                zone: { left: 24, width: 11 },
                color: '#0891B2',
                level: 'foundation',
                name: 'Reduction',
                matchClue: 'How far the signal is turned down when the gate is closed — Logic’s name for what Ableton calls Floor.',
                description: 'Sets how much the signal is attenuated when the gate is closed — this is Logic’s name for what Ableton calls Floor. At −100 dB the gate closes to silence; at gentler settings like −20 dB some signal still passes when “closed”. Treat Reduction as a dial, not a cliff: full attenuation produces an unnatural chopped sound, and around −20 dB sounds far more natural than total mute.',
                questions: [
                    { q: 'Why not always gate to complete silence?', a: 'Total silence between notes removes all room tone and background, creating an obvious gate-is-working effect that examiners describe as unnatural chopping. Reducing by around 20 dB keeps a hint of ambience so the gating is transparent. Save full attenuation for deliberate effects — the 1980s gated snare wants the dramatic cut.' },
                    { q: 'Is a gate with partial reduction still a gate?', a: 'Conceptually it is behaving as a downward expander — a gate is the extreme case, a 1:∞ expander that fully silences below the threshold. Partial reduction gives a gentler expansion that cleans up bleed while sounding natural. Naming the gate as an extreme downward expander is exactly the sort of connection the written paper rewards.' },
                ],
            },
            {
                id: 'hysteresis',
                label: 'D',
                zone: { left: 36, width: 11 },
                color: '#D97706',
                level: 'advanced',
                name: 'Hysteresis',
                matchClue: 'How far below the threshold the signal must fall before the gate closes again — Logic’s name for Ableton’s Return.',
                description: 'Sets a second, lower level below the {{B}} threshold that the signal must drop past before the gate closes — Logic’s name for what Ableton calls Return. At −3 dB, a gate opening at −50 dB will not close until the signal falls below −53 dB. This gap stops the gate rapidly opening and closing (“chattering”) when the signal hovers around the threshold. Naming Hysteresis, and what it prevents, lifts an answer.',
                questions: [
                    { q: 'What is gate chatter and how does hysteresis stop it?', a: 'Chatter is the ugly stutter of a gate snapping open and shut many times a second when the signal sits right at the threshold. Hysteresis separates the opening level from the closing level, so small wobbles around the threshold no longer flip the gate state — the signal has to fall clearly below before the gate shuts.' },
                    { q: 'Is Hysteresis the same thing as Ableton’s Return?', a: 'Yes — same control, different name. Ableton’s Gate calls it Return; Logic’s Noise Gate calls it Hysteresis (the engineering term). The exam shows you unfamiliar devices on purpose, so knowing the concept under both names means you can read whichever interface the paper prints.' },
                ],
            },
            {
                id: 'attack',
                label: 'E',
                zone: { left: 48, width: 11 },
                color: '#2563EB',
                level: 'foundation',
                name: 'Attack',
                matchClue: 'How quickly the gate opens once the signal crosses the threshold.',
                description: 'How quickly the gate opens once the signal exceeds the {{B}} threshold. Fast attack (Logic’s is set in ms, here 3 ms) preserves drum transients; slower attack softens the front of each sound as the gate fades in. For percussive material you almost always want attack fast, or the gate clips the very transient you are trying to keep.',
                questions: [
                    { q: 'Why does a slow attack dull drum hits?', a: 'The transient — the first few milliseconds of the hit — carries the punch. If the gate takes 20 ms to open, the transient is already over by the time signal passes at full level, so the hit sounds soft and swallowed. Fast attack lets the front of the hit through intact.' },
                    { q: 'When would a slower attack be useful?', a: 'On non-percussive material — a vocal or a pad — a very fast attack can produce an audible click as the gate snaps open. A slightly slower attack fades the gate in smoothly. Match the attack to the material: fast for drums, gentler for sustained sources.' },
                ],
            },
            {
                id: 'hold',
                label: 'F',
                zone: { left: 60, width: 11 },
                color: '#7C3AED',
                level: 'intermediate',
                name: 'Hold',
                matchClue: 'The minimum time the gate stays open once triggered, before release begins.',
                description: 'Forces the gate to stay fully open for a minimum time (here 40 ms) after it triggers, before the {{G}} release phase begins. Hold prevents very short retriggers on sounds that dip momentarily — and it is the control behind the classic gated-reverb snare: a big reverb, a gate with a deliberate hold time, then a hard cut.',
                questions: [
                    { q: 'What problem does hold solve that hysteresis does not?', a: 'Hysteresis manages signals hovering AROUND the threshold; hold manages sounds whose level dips briefly DURING a hit — a snare with a complex decay can fall below the threshold for a moment and retrigger the gate. Hold keeps the gate open through those dips so each hit reads as one event, not several.' },
                    { q: 'How does hold create the 1980s gated snare?', a: 'Put a huge reverb on the snare, then gate the result: the hold time sets how much of the reverb blooms through before the gate slams shut. Around 100–200 ms of hold gives the explosive burst-then-silence that defines the sound. The gate’s hold, not the reverb’s decay, decides where the tail dies.' },
                ],
            },
            {
                id: 'release',
                label: 'G',
                zone: { left: 72, width: 11 },
                color: '#DB2777',
                level: 'foundation',
                name: 'Release',
                matchClue: 'How quickly the gate closes once the signal falls below the threshold (and any hold has elapsed).',
                description: 'How quickly the gate fades closed once the signal drops below the {{B}} threshold and the {{F}} hold time has passed. Fast release cuts tails dead — dramatic, but risks chopping natural decays. Slower release lets the gate close musically with the sound. Logic’s release here is 10 ms: tight and percussive.',
                questions: [
                    { q: 'What does too fast a release sound like?', a: 'The natural decay of each note or drum gets amputated — the sound stops with an audible snap instead of dying away. On anything with a tail (toms, room mics, vocals) that reads as obviously processed. Lengthen the release until the close becomes inaudible, then stop.' },
                    { q: 'How do attack, hold and release fit together?', a: 'They are the gate’s envelope: attack shapes how the gate OPENS, hold sets a minimum open time, release shapes how it CLOSES. Read them left to right on the interface as the life of one drum hit: snap open, stay open through the hit, then close at a chosen speed.' },
                ],
            },
            {
                id: 'lookahead',
                label: 'H',
                zone: { left: 84, width: 11 },
                color: '#57534E',
                level: 'advanced',
                name: 'Lookahead',
                matchClue: 'Lets the gate react slightly before the signal arrives, so even instant transients open it cleanly.',
                description: 'Delays the audio path slightly so the gate’s detector hears the signal early — it can open the gate BEFORE the transient arrives, catching even the fastest hits with zero clipped attack. Ableton’s Gate has no Lookahead knob on its face; the cost in any DAW is added latency, which matters when tracking live but not when mixing.',
                questions: [
                    { q: 'Why would lookahead be better than just a faster attack?', a: 'Even a 0 ms attack can only react once the signal has already crossed the threshold — the first fraction of the transient is always at risk. Lookahead sidesteps the problem by letting the gate act on a preview of the signal, so the gate is already open when the transient plays. The attack setting then shapes taste rather than fighting physics.' },
                    { q: 'What is the trade-off of using lookahead?', a: 'Latency. The audio has to be delayed by the lookahead time for the trick to work, so the track plays fractionally late relative to the rest of the session unless the DAW compensates. Fine in a mix where the DAW’s latency compensation handles it; a problem when a performer is monitoring live through the gate.' },
                ],
            },
        ],
    },
};

export default gateConfig;
