const gateConfig = {
    imageSrc: '/images/explorers/ableton-gate.png',
    imageAlt: 'Ableton Live Gate effect interface showing threshold, return, attack, hold, release, floor, and sidechain controls',
    title: 'Gate Controls Explorer',
    instruction: 'Drag a cable from the floating box to a coloured zone below the image to learn what that control does.',
    hotspots: [
        {
            id: 'sidechain',
            label: 'A',
            zone: { left: 0, width: 13 },
            color: '#E8590C',
            level: 'advanced',
            name: 'Sidechain',
            matchClue: 'Routes a separate audio source to trigger the gate, rather than the signal being processed itself.',
            description: 'Enables sidechain gating, where the gate listens to an external signal (the "key" or "trigger") instead of the signal it is processing. For example, a hi-hat pattern can trigger a gate on a synth pad, creating a rhythmic chopping effect. The {{C}} threshold still controls when the gate opens — sidechain only changes what signal is being monitored.',
            questions: [
                { q: 'When would I use sidechain gating?', a: 'Sidechain gating is commonly used to create rhythmic effects — routing a drum pattern to trigger a gate on a pad or vocal creates a choppy, rhythmic texture. It is also used in live sound to gate a snare mic using the snare itself as the trigger from a cleaner source, reducing bleed from other drums.' },
                { q: 'How is sidechain gating different from sidechain compression?', a: 'With sidechain compression, the external signal controls how much the volume is reduced — it ducks the audio. With sidechain gating, the external signal controls whether the audio passes through at all. The gate is either open or closed (or partially closed, depending on the {{G}} floor), making the effect much more dramatic.' },
                { q: 'What signal should I route to the sidechain input?', a: 'Route whichever signal you want to use as the trigger. For rhythmic chopping, use a drum loop or click track. For cleaning up drum bleed, use the close-mic of the drum you want to isolate. In Ableton, set the "Sidechain" source dropdown to the track you want to trigger from.' },
            ],
        },
        {
            id: 'return',
            label: 'B',
            zone: { left: 14, width: 13 },
            color: '#D97706',
            level: 'advanced',
            name: 'Return',
            matchClue: 'The level below the threshold at which the gate closes again, preventing rapid on-off switching.',
            description: 'Also called hysteresis, this sets how far below the {{C}} threshold the signal must drop before the gate closes. For example, if the threshold is -20 dB and return is set to -3 dB, the gate opens at -20 dB but will not close again until the signal drops below -23 dB. This prevents the gate from rapidly opening and closing (chattering) when the signal hovers around the threshold.',
            questions: [
                { q: 'What is gate chatter and how does return prevent it?', a: 'Gate chatter happens when a signal hovers right at the {{C}} threshold level — the gate rapidly opens and closes, creating an unpleasant stuttering or buzzing sound. Return creates a gap between the opening and closing levels. The signal must drop further below the threshold before the gate closes, so small level fluctuations near the threshold do not cause rapid switching.' },
                { q: 'What is a good starting value for return?', a: 'A return of -3 dB to -6 dB below the threshold works well in most situations. If you hear chattering, increase the return value. If the gate is staying open too long and letting through unwanted noise at the end of a sound, reduce it. The goal is a smooth, natural gate action without audible switching artefacts.' },
            ],
        },
        {
            id: 'threshold',
            label: 'C',
            zone: { left: 28, width: 13 },
            color: '#059669',
            level: 'foundation',
            name: 'Threshold',
            matchClue: 'The level above which the gate opens to let the signal through.',
            description: 'Sets the level (in dB) that the signal must exceed for the gate to open. When the signal is above this level, audio passes through. When it drops below, the gate closes and the signal is attenuated down to the {{G}} floor level. The {{B}} return control adds hysteresis so the gate does not chatter at the threshold boundary.',
            questions: [
                { q: 'What happens if I set the threshold too high?', a: 'If the threshold is too high, the gate will cut off parts of the signal you want to keep. Quiet notes, the tails of drum hits, or softer vocal phrases may be silenced because they do not reach the threshold. You will hear unnatural, choppy cutoffs.' },
                { q: 'What happens if I set the threshold too low?', a: 'If the threshold is too low, the gate stays open most of the time, allowing bleed and noise through — defeating the purpose. The gate only closes during the very quietest moments. You want the threshold just above the level of the unwanted noise but below the level of the signal you want to keep.' },
                { q: 'How do I find the right threshold?', a: 'Play back the audio and watch the input meter. Identify the level of the noise or bleed you want to remove, and set the threshold just above that. Then listen carefully to make sure the gate opens fully for the wanted signal without cutting off any tails or quiet passages. Adjust the {{B}} return if the gate is chattering.' },
            ],
        },
        {
            id: 'attack',
            label: 'D',
            zone: { left: 42, width: 13 },
            color: '#2563EB',
            level: 'foundation',
            name: 'Attack',
            matchClue: 'How quickly the gate opens once the signal exceeds the threshold.',
            description: 'Controls how quickly the gate opens when the signal crosses the {{C}} threshold. A fast attack (< 1 ms) opens the gate almost instantly, preserving sharp transients like drum hits. A slower attack softens the onset of the sound, which can create fade-in effects or smooth out harsh transients.',
            questions: [
                { q: 'Should I always use a fast attack on a gate?', a: 'For drums and percussive sounds, yes — a fast attack (0.01-0.5 ms) ensures the initial transient is not lost. But for vocals or sustained instruments, a slightly slower attack (1-5 ms) can sound more natural and avoid clicks. An extremely fast attack can sometimes produce an audible click as the gate snaps open.' },
                { q: 'Can a gate click when it opens?', a: 'Yes. If the attack is extremely fast and the signal is already at a high level when the gate opens, the sudden jump from silence (or the {{G}} floor level) to the full signal can create an audible click. A slightly slower attack or raising the {{G}} floor can help eliminate this artefact.' },
                { q: 'How does gate attack differ from compressor attack?', a: 'A compressor attack controls how quickly gain reduction begins — it is about reducing volume. A gate attack controls how quickly the gate opens to let signal through — it is about allowing volume. They are opposite actions: compression reacts to loud signals by turning down; gating reacts to loud signals by turning up (opening).' },
            ],
        },
        {
            id: 'hold',
            label: 'E',
            zone: { left: 56, width: 13 },
            color: '#9B7530',
            level: 'foundation',
            name: 'Hold',
            matchClue: 'The minimum time the gate stays open after the signal drops below the threshold.',
            description: 'Sets the minimum time the gate remains open after the signal falls below the {{C}} threshold, before the {{F}} release phase begins. This prevents the gate from closing prematurely on signals with natural volume dips, like a drummer hitting slightly softer mid-phrase. Hold ensures a consistent minimum open time regardless of signal level.',
            questions: [
                { q: 'Why do I need hold if I have release?', a: 'Hold and {{F}} release do different things. Hold keeps the gate fully open for a set time after the signal drops below the threshold — the signal passes through at full volume. Release then controls how quickly the gate fades closed after the hold time expires. Without hold, the release would start immediately, and short dips in level could trigger premature closing.' },
                { q: 'What is a good hold time for drums?', a: 'For snare drums, 20-50 ms works well — long enough to capture the full body of the hit without cutting it short. For kick drums, 30-80 ms. For toms, 50-150 ms depending on how much ring you want to keep. Listen for the natural decay of the drum and set hold to capture at least the body of the sound.' },
                { q: 'When would I use a very long hold time?', a: 'A long hold time (200+ ms) is useful when gating vocals or sustained instruments where natural phrasing has brief quiet moments. It keeps the gate open through short pauses so the gate does not cut mid-phrase. Combined with a longer {{F}} release, this creates smooth, natural-sounding gating.' },
            ],
        },
        {
            id: 'release',
            label: 'F',
            zone: { left: 70, width: 14 },
            color: '#B85A3F',
            level: 'foundation',
            name: 'Release',
            matchClue: 'How quickly the gate closes after the hold time has expired.',
            description: 'Controls how quickly the gate fades from fully open down to the {{G}} floor level, after the {{E}} hold time has expired. A fast release cuts the signal off sharply, which can sound unnatural. A slower release creates a gradual fade-out that sounds more natural, especially on drums with resonant tails or sustained instruments.',
            questions: [
                { q: 'What happens if the release is too fast?', a: 'A very fast release cuts the sound off abruptly, which can sound unnatural — like someone hitting a mute button. On drums, it removes the natural decay and room ambience. On vocals, it chops off word endings. You may also hear a click if the waveform is cut at a non-zero crossing point.' },
                { q: 'What happens if the release is too slow?', a: 'A very slow release means the gate takes a long time to close, so noise and bleed continue to come through during the fade-out. This reduces the effectiveness of the gate — you wanted to remove that noise, but a slow release lets it linger. Find the balance between natural-sounding decay and effective noise removal.' },
                { q: 'How do hold and release work together for drums?', a: 'For a snare drum: set {{E}} hold to around 30-50 ms to capture the body of the hit, then set release to 50-100 ms so the tail fades out naturally rather than being cut off. The hold keeps the gate fully open for the initial hit, then the release creates a smooth fade. Without hold, the release would start too early and thin out the sound.' },
            ],
        },
        {
            id: 'floor',
            label: 'G',
            zone: { left: 85, width: 15 },
            color: '#0891B2',
            level: 'foundation',
            name: 'Floor',
            matchClue: 'The amount of attenuation applied when the gate is closed — how quiet the signal gets.',
            description: 'Sets the level the signal is reduced to when the gate is closed. At -inf dB (fully closed), the gate completely silences the signal. At higher floor values like -12 dB or -6 dB, some signal still passes through even when the gate is closed, which sounds more natural and avoids the "dead silence" effect between notes.',
            questions: [
                { q: 'Why would I not set the floor to -inf (complete silence)?', a: 'Complete silence between notes or drum hits can sound unnatural — it removes all room ambience and background, creating an obvious "gate is on" effect. Setting the floor to -20 dB or -12 dB allows some room tone and bleed through when the gate is closed, which sounds more natural while still significantly reducing noise. This is especially important for live recordings where the room sound is part of the character.' },
                { q: 'What floor setting should I use for drums?', a: 'For close-miked drums in a studio, -inf works well because there is less room sound to preserve. For live recordings or overhead mics, try -20 to -12 dB so some room ambience remains. For extreme gated drum effects (like 80s gated reverb), use -inf for the dramatic cut-off. Always compare gated and ungated to check it sounds natural.' },
                { q: 'How is floor different from a noise gate that just mutes?', a: 'A simple noise gate is either open or closed — binary on/off. The floor control turns a gate into an expander by allowing partial attenuation. Instead of muting completely, it reduces the signal by a set amount. This gives you much more control and sounds far more natural. Many engineers prefer a -20 dB floor over complete silence for this reason.' },
            ],
        },
    ],
};

export default gateConfig;
