const operatorConfig = {
    imageSrc: '/images/explorers/ableton-operator.png',
    imageAlt: 'Ableton Live Operator synthesiser interface showing four oscillator operators, algorithm routing, envelope, filter and LFO controls',
    title: 'Operator Controls Explorer',
    instruction: 'Drag a cable from the floating box to a coloured zone below the image to learn what that control does.',
    hotspots: [
        {
            id: 'oscillators',
            label: 'A',
            zone: { left: 0, width: 12 },
            color: '#E8590C',
            level: 'foundation',
            name: 'Oscillators (A-D)',
            matchClue: 'The four operator tabs that each generate or modulate a sound using a selectable waveform.',
            description: 'Operator has four independent oscillators, labelled A, B, C, and D. Each can generate a waveform (sine, sawtooth, square, triangle, noise, or custom shapes). Whether an oscillator produces audible sound or modulates another oscillator depends on the {{D}} algorithm — in FM synthesis, some oscillators are "carriers" (you hear them) and others are "modulators" (they shape the tone of a carrier). Click each tab to access its individual settings.',
            questions: [
                { q: 'What is the difference between a carrier and a modulator?', a: 'A carrier oscillator produces the sound you actually hear — its {{B}} frequency determines the pitch. A modulator oscillator is not heard directly — instead, its waveform rapidly varies the frequency of a carrier, creating complex timbres and harmonics. This is FM (Frequency Modulation) synthesis. The {{D}} algorithm determines which oscillators are carriers and which are modulators.' },
                { q: 'Which waveforms should I start with?', a: 'Sine waves are the purest tone with no harmonics — ideal for learning FM synthesis because the modulation results are predictable. Sawtooth waves are rich in harmonics and sound bright and buzzy. Square waves have a hollow, woody character. Triangle waves are similar to sine but slightly brighter. Start with sine waves on all four oscillators to understand FM, then experiment with others.' },
                { q: 'Do I need to use all four oscillators?', a: 'No — you can use as few as one. A single sine wave oscillator gives you a pure tone. Two oscillators (one carrier, one modulator) give you basic FM synthesis. Three or four add more complexity and richness. The {{C}} level of each oscillator controls how much it contributes. Set unused oscillators to zero level. Start simple and add complexity as needed.' },
            ],
        },
        {
            id: 'coarse-fine',
            label: 'B',
            zone: { left: 12, width: 14 },
            color: '#D97706',
            level: 'foundation',
            name: 'Coarse / Fine',
            matchClue: 'Sets the frequency ratio of each oscillator relative to the played note.',
            description: 'Coarse sets the frequency ratio in whole numbers — a ratio of 1 means the oscillator plays at the note\'s fundamental frequency, 2 means double (one octave up), 0.5 means half (one octave down). Fine adds precise detuning in cents for subtle pitch variations. For FM synthesis, the ratio between a modulator and its carrier determines the harmonic character — integer ratios (1, 2, 3, 4) create harmonic tones, while non-integer ratios create inharmonic, metallic, or bell-like timbres.',
            questions: [
                { q: 'Why do integer ratios sound harmonic?', a: 'Integer frequency ratios (1:1, 2:1, 3:1) produce overtones that align with the natural harmonic series — the same overtones found in acoustic instruments. This sounds musical and tonal. Non-integer ratios (1.41, 2.76) produce overtones that do not align with the harmonic series, creating inharmonic sounds like bells, metallic hits, and noise. This is one of the most powerful features of FM synthesis.' },
                { q: 'What does detuning with Fine do?', a: 'Fine tuning shifts the pitch by small amounts (cents). When two oscillators are slightly detuned from each other, their waveforms phase in and out, creating a natural chorusing effect that sounds wider and more alive. Try setting two carriers to a ratio of 1 with one detuned 5-10 cents — this is the classic "fat" unison sound used in pads and leads.' },
                { q: 'What ratios create useful FM sounds?', a: 'Ratio 1:1 (modulator same as carrier): adds brightness and edge, like an overdriven sound. Ratio 2:1: adds octave harmonics, creating a brighter, more complex tone. Ratio 3:1 or 4:1: adds higher harmonics, useful for creating plucked or bell-like sounds. Ratio 0.5:1: modulates below the fundamental, creating growling, sub-bass effects. The {{C}} level of the modulator controls how intense the FM effect is.' },
            ],
        },
        {
            id: 'level',
            label: 'C',
            zone: { left: 26, width: 12 },
            color: '#059669',
            level: 'foundation',
            name: 'Level',
            matchClue: 'Controls the output volume of each oscillator, which also determines FM modulation intensity.',
            description: 'Sets the output level of the selected oscillator. For carrier oscillators, this controls how loud that oscillator is in the final sound. For modulator oscillators, the level controls the modulation depth — how much the modulator affects the carrier\'s frequency. A low modulator level creates subtle timbral changes; a high level creates dramatic, complex, and potentially harsh FM tones. This makes Level one of the most expressive controls in Operator.',
            questions: [
                { q: 'Why does modulator level change the tone so dramatically?', a: 'In FM synthesis, the modulator\'s level directly controls the "modulation index" — how far the carrier\'s frequency is being pushed up and down. At low levels, only a few extra harmonics are added (subtle brightness). At high levels, many harmonics are generated across the spectrum, creating complex, sometimes aggressive tones. Small level changes on a modulator can completely transform the sound.' },
                { q: 'How should I set levels when building a sound?', a: 'Start with all modulators at zero level, so you hear only the pure carrier waveforms. Then slowly increase each modulator\'s level to hear how it affects the timbre. This way you build the sound gradually and understand what each modulator contributes. For carriers, balance their levels to create the desired mix between the audible oscillators.' },
                { q: 'Can I automate the level for expressive sounds?', a: 'Yes — automating a modulator\'s level over time creates evolving timbres. This is how many classic FM sounds work: the {{E}} envelope is applied to the modulator level so it starts bright (high modulation) and fades to a pure tone (low modulation), mimicking how acoustic instruments lose harmonics as they decay. Electric piano and bell sounds rely heavily on this technique.' },
            ],
        },
        {
            id: 'algorithm',
            label: 'D',
            zone: { left: 38, width: 14 },
            color: '#2563EB',
            level: 'foundation',
            name: 'Algorithm',
            matchClue: 'Determines how the four oscillators are routed — which modulate which, and which produce audible sound.',
            description: 'The algorithm defines the routing between the four oscillators. It determines which oscillators are carriers (producing audible sound) and which are modulators (shaping the tone of carriers). Operator offers 11 algorithms ranging from a simple stack (all four in series, one carrier) to fully parallel (all four as independent carriers, no FM). The algorithm fundamentally changes the synthesis method — serial routing creates FM synthesis, parallel routing creates additive synthesis.',
            questions: [
                { q: 'What is the difference between FM and additive synthesis?', a: 'FM (Frequency Modulation) synthesis uses one oscillator to modulate another\'s frequency, creating complex harmonics from simple waveforms. Additive synthesis layers multiple carriers together, each producing its own tone, and mixes them. In Operator, serial algorithms (oscillators feeding into each other) create FM synthesis. Parallel algorithms (all oscillators outputting directly) create additive synthesis. Many algorithms combine both approaches.' },
                { q: 'Which algorithm should I start with?', a: 'Start with a simple two-oscillator algorithm where B modulates A. This gives you one carrier (A, which you hear) and one modulator (B, which shapes A\'s tone). Adjust B\'s {{B}} ratio and {{C}} level to hear classic FM sounds. Once comfortable, try algorithms with more modulators feeding into one carrier for richer tones, or parallel algorithms for layered sounds.' },
                { q: 'How do I read the algorithm diagram?', a: 'In the algorithm display, oscillators that output to the bottom (the speaker icon) are carriers — you hear them. Oscillators that feed into another oscillator are modulators — they shape the sound but are not heard directly. An arrow from D to C means D modulates C. The further up the chain an oscillator sits, the more indirect its influence on the final sound.' },
            ],
        },
        {
            id: 'envelope',
            label: 'E',
            zone: { left: 52, width: 16 },
            color: '#9B7530',
            level: 'foundation',
            name: 'Envelope (ADSR)',
            matchClue: 'Shapes how the oscillator\'s level changes over time from the moment a note is pressed to when it is released.',
            description: 'Each oscillator has its own ADSR envelope that controls how its level changes over time. Attack sets how quickly the level rises when a note is pressed. Decay sets how quickly it falls from the peak to the sustain level. Sustain sets the level held while the note is held. Release sets how quickly the level fades after the note is released. On a modulator, the envelope shapes the timbral change over time rather than volume.',
            questions: [
                { q: 'What does ADSR stand for?', a: 'Attack: time from silence to peak level when you press a key. Decay: time from the peak down to the sustain level. Sustain: the level held for as long as you hold the key (this is a level, not a time). Release: time from the sustain level back to silence when you release the key. Together, these four parameters describe the complete life of a note from press to silence.' },
                { q: 'How does the envelope on a modulator affect the sound?', a: 'On a modulator, the envelope controls how the FM modulation intensity changes over time. A fast attack and decay with low sustain on a modulator means the sound starts bright (lots of harmonics) and quickly becomes pure — this is exactly how a plucked string or struck bell behaves. The {{C}} level sets the peak modulation amount, and the envelope shapes how it evolves.' },
                { q: 'What envelope settings create common sounds?', a: 'Plucked string/bell: zero attack, fast decay, zero sustain — sound appears instantly and fades. Pad/organ: slow attack, no decay, full sustain, slow release — sound fades in and sustains. Percussion: zero attack, medium decay, zero sustain — a quick hit. Swell: slow attack, no decay, full sustain — gradual fade-in while held. Apply these to both carriers (volume shape) and modulators (timbre shape).' },
            ],
        },
        {
            id: 'filter',
            label: 'F',
            zone: { left: 68, width: 14 },
            color: '#B85A3F',
            level: 'advanced',
            name: 'Filter',
            matchClue: 'A subtractive filter applied after the FM synthesis, removing frequencies from the combined sound.',
            description: 'Operator includes a multimode filter that processes the combined output of all carrier oscillators. It offers low-pass, high-pass, band-pass, and notch types. The filter adds subtractive synthesis capability on top of the FM engine — you can use FM to create a harmonically rich sound, then sculpt it with the filter. The filter has its own envelope for time-varying cutoff, and can be modulated by the {{G}} LFO.',
            questions: [
                { q: 'Why use a filter when FM synthesis already shapes harmonics?', a: 'FM synthesis creates harmonics by modulating frequencies, but the results can be unpredictable and hard to control precisely. A filter gives you familiar subtractive control — a low-pass filter can tame harsh high-frequency content from aggressive FM settings, while a band-pass can focus the sound. Combining FM and subtractive synthesis gives you the best of both worlds.' },
                { q: 'How does the filter envelope work?', a: 'The filter has its own ADSR envelope that controls the cutoff frequency over time, independent of the oscillator envelopes. A common technique: set the filter cutoff low and use the envelope to sweep it up on the attack, then back down — this creates a "wah" or "pluck" effect on top of whatever FM timbre you have built. The envelope amount controls how far the cutoff sweeps.' },
                { q: 'When should I use the filter versus adjusting modulator levels?', a: 'Use modulator {{C}} levels and envelopes for broad timbral shaping — this is the core of FM synthesis. Use the filter for final tone sculpting — removing unwanted harshness, adding a resonant peak, or creating filter sweep effects. Think of FM as building the raw material and the filter as polishing it. Many classic FM sounds use no filter at all; others rely heavily on it.' },
            ],
        },
        {
            id: 'lfo',
            label: 'G',
            zone: { left: 82, width: 18 },
            color: '#0891B2',
            level: 'advanced',
            name: 'LFO',
            matchClue: 'A low frequency oscillator that adds continuous modulation such as vibrato, tremolo, or filter wobble.',
            description: 'The LFO (Low Frequency Oscillator) generates a slow, repeating waveform that modulates other parameters over time. It can target oscillator pitch (creating vibrato), oscillator level (creating tremolo), filter cutoff (creating wah effects), or panning. The Rate sets the speed — slow rates create gentle movement, faster rates create dramatic wobbles. The Amount controls how intense the modulation is. The LFO can be free-running or synced to tempo.',
            questions: [
                { q: 'What is the difference between vibrato and tremolo?', a: 'Vibrato is a periodic variation in pitch — the LFO modulates the oscillator frequency, making the note waver slightly higher and lower. Tremolo is a periodic variation in volume — the LFO modulates the oscillator level, making the sound pulse louder and quieter. Both add life and movement to sustained sounds. Vibrato is typically subtle (a few cents of pitch variation); tremolo can be more dramatic.' },
                { q: 'What LFO rate should I use?', a: 'For subtle vibrato or tremolo, use slow rates around 4-6 Hz — this matches the natural vibrato speed of a singer or string player. For rhythmic effects like a pulsing pad or wobble bass, sync the LFO to tempo and use note values (1/4, 1/8, 1/16). For extreme sound design, faster rates (10-20 Hz) create buzzing, ring-modulation-like effects as the LFO enters audio-rate territory.' },
                { q: 'How does the LFO interact with the filter?', a: 'When the LFO is routed to the {{F}} filter cutoff, it creates a repeating sweep — the filter opens and closes rhythmically. This is the classic "wobble" effect used in dubstep and electronic music. Set a low-pass filter with moderate resonance, route the LFO to filter cutoff with a high amount, and sync the rate to tempo. The LFO waveform shape (sine, square, sawtooth) determines the character of the wobble.' },
            ],
        },
    ],
};

export default operatorConfig;
