const reverbConfig = {
    imageSrc: '/images/explorers/ableton-reverb.png',
    imageAlt: 'Ableton Live Reverb effect interface showing input processing, early reflections, decay, diffusion, damping and output controls',
    title: 'Reverb Controls Explorer',
    instruction: 'Drag a cable from the floating box to a coloured zone below the image to learn what that control does.',
    hotspots: [
        {
            id: 'input-processing',
            label: 'A',
            zone: { left: 0, width: 14 },
            color: '#E8590C',
            level: 'advanced',
            name: 'Input Processing',
            matchClue: 'Filters the signal before it enters the reverb, controlling which frequencies are sent into the reverberant space.',
            description: 'The input high-cut and low-cut filters shape the signal before it reaches the reverb algorithm. The low-cut removes bass frequencies from the reverb input, preventing muddy low-end buildup. The high-cut removes brightness, creating a darker, more distant-sounding reverb. These filters only affect what goes into the reverb: the dry signal passes through untouched.',
            questions: [
                { q: 'Why would I filter the input rather than the output?', a: 'Filtering the input prevents unwanted frequencies from ever entering the reverb, so they never build up in the {{D}} decay tail. If you filter the output instead, those frequencies have already been processed and can still cause muddiness or harshness during the decay. Input filtering is more efficient and sounds cleaner: it is like choosing what goes into a room rather than trying to fix the echo afterwards.' },
                { q: 'What is a good low-cut setting for reverb?', a: 'For most mixing situations, cutting below 200-400 Hz prevents bass buildup in the reverb tail. Vocals and guitars typically benefit from a low-cut around 300 Hz. Drums might need a higher cut (400-600 Hz) to keep the low end tight. The goal is to keep the reverb clear and defined without it muddying up the bottom end of your mix.' },
                { q: 'When would I use the high-cut on the input?', a: 'High-cutting the input creates a warmer, more natural reverb that simulates how real rooms absorb high frequencies. Try cutting above 6-8 kHz for a vintage, warm reverb character. Cutting more aggressively (above 3-4 kHz) creates a dark, distant effect. This is different from the {{F}} damping controls, which affect how high frequencies decay over time rather than what enters the reverb.' },
            ],
        },
        {
            id: 'early-reflections',
            label: 'B',
            zone: { left: 14, width: 14 },
            color: '#D97706',
            level: 'advanced',
            name: 'Early Reflections',
            matchClue: 'The first distinct echoes that arrive before the main reverb tail, conveying the size and shape of the space.',
            description: 'Early reflections are the first sound waves that bounce off the nearest surfaces (walls, floor, ceiling) and reach the listener before the dense reverb tail develops. The Shape control adjusts the envelope of these early reflections: how they build up and decay. Spin adds modulation to prevent a static, metallic quality. Early reflections are crucial for perceiving the size and character of a space.',
            questions: [
                { q: 'Why are early reflections important?', a: 'Our brains use early reflections to judge the size, shape, and material of a room. They arrive within the first 50-100 ms after the direct sound and tell us whether we are in a small tiled bathroom (bright, quick reflections) or a large concert hall (spread out, darker reflections). Without early reflections, reverb sounds artificial and disconnected from any real space.' },
                { q: 'What does the Shape control do?', a: 'Shape adjusts the amplitude envelope of the early reflections over time. A lower Shape value creates a sharp initial attack that decays quickly: like a small, reflective room. A higher value creates a gradual build-up: like a larger space where reflections arrive more spread out. It changes the perceived geometry of the virtual room.' },
                { q: 'How do early reflections relate to pre-delay?', a: 'The {{C}} pre-delay sets the gap between the direct sound and the first reflections arriving. Early reflections then fill the space between this initial gap and the onset of the main {{D}} decay tail. Together, pre-delay and early reflections define how the listener perceives distance: longer pre-delay with gradual early reflections suggests a large space.' },
            ],
        },
        {
            id: 'predelay',
            label: 'C',
            zone: { left: 28, width: 12 },
            color: '#059669',
            level: 'foundation',
            name: 'Pre-Delay',
            matchClue: 'The time gap between the original sound and the first reverb reflections arriving.',
            description: 'Pre-delay sets the time (in milliseconds) between the dry signal and the onset of the reverb. In a real room, this gap exists because sound takes time to travel to a surface, reflect, and return. A longer pre-delay (30-80 ms) separates the dry sound from the reverb, improving clarity. The original attack is heard cleanly before the reverb begins. A shorter pre-delay (0-15 ms) blends the reverb tightly with the source.',
            questions: [
                { q: 'How does pre-delay affect clarity?', a: 'Pre-delay creates a gap between the initial transient and the reverb onset. This means the attack of a vocal consonant, a drum hit, or a guitar pick is heard clearly before the reverb fills in behind it. Without pre-delay, the reverb starts immediately and can smear the transient, making the sound less defined. For vocals in a dense mix, 30-60 ms of pre-delay is common.' },
                { q: 'What pre-delay values correspond to different room sizes?', a: 'In a real room, pre-delay depends on the distance to the nearest reflective surface. A small room (3-5 metres) produces pre-delay around 10-20 ms. A medium room (10-15 metres) around 30-50 ms. A large hall (20+ metres) around 60-100 ms. These are approximate: the speed of sound is roughly 1 ms per 30 cm of travel (there and back).' },
                { q: 'Can I sync pre-delay to the tempo?', a: 'While Ableton\'s Reverb does not have a sync button for pre-delay, you can calculate musically useful values. At 120 BPM, a 1/64 note is about 31 ms, a 1/32 note is 62 ms. Setting pre-delay to a rhythmic subdivision keeps the reverb onset in time with the music, preventing it from clashing with the groove. This is a professional mixing technique for keeping reverb transparent.' },
            ],
        },
        {
            id: 'decay',
            label: 'D',
            zone: { left: 40, width: 14 },
            color: '#2563EB',
            level: 'foundation',
            name: 'Decay Time',
            matchClue: 'How long the reverb tail lasts before fading to silence.',
            description: 'Decay time (also called RT60 in acoustics) sets how long the reverb tail sustains before it fades away. Short decay (0.5-1.5 s) suggests a small, absorptive room: a bedroom or vocal booth. Medium decay (1.5-3 s) suggests a larger room or studio. Long decay (3-8 s+) suggests a cathedral, concert hall, or large open space. The Size parameter works alongside decay to define the character of the space.',
            questions: [
                { q: 'What is RT60?', a: 'RT60 is the standard measurement of reverb time in acoustics. It is the time it takes for the reverb to decay by 60 dB (effectively to silence). A concert hall might have an RT60 of 2-3 seconds. A recording studio control room is designed for 0.3-0.5 seconds. The decay control in the reverb plugin is directly equivalent to setting the RT60 of your virtual space.' },
                { q: 'How do I choose the right decay time?', a: 'Match the decay to the tempo and density of the music. Fast songs need shorter decay so the reverb clears before the next beat. Slow ballads can use longer decay for atmosphere. As a starting point: for pop vocals, try 1.5-2.5 s. For snare drums, 1-2 s. For ambient pads, 3-6 s. If the reverb sounds "washy" or cluttered, shorten the decay.' },
                { q: 'How does decay interact with the damping controls?', a: 'The decay time sets the overall length of the reverb tail, but the {{F}} damping controls determine how different frequencies decay within that time. High-frequency damping causes brightness to fade faster than the bass: mimicking how soft furnishings absorb treble in a real room. So the overall decay might be 3 seconds, but high frequencies might fade in 1.5 seconds while the bass sustains the full 3 seconds.' },
            ],
        },
        {
            id: 'diffusion',
            label: 'E',
            zone: { left: 54, width: 13 },
            color: '#9B7530',
            level: 'advanced',
            name: 'Diffusion',
            matchClue: 'How densely packed the reflections are within the reverb tail.',
            description: 'Diffusion controls the density and spacing of individual reflections within the reverb tail. High diffusion creates a thick, smooth, lush reverb where individual reflections blur together: ideal for vocals, pads, and orchestral instruments. Low diffusion creates a more sparse, grainy reverb where you can hear individual echoes. Useful for percussive sounds or when you want a more natural, room-like character.',
            questions: [
                { q: 'What does high diffusion sound like versus low diffusion?', a: 'High diffusion sounds smooth, dense, and washy: like a large reverberant cathedral where thousands of reflections merge into a continuous sound. Low diffusion sounds more textured and granular: you can hear individual echoes bouncing around, similar to a room with hard, flat walls. Extremely low diffusion approaches a distinct echo or flutter effect rather than a smooth reverb tail.' },
                { q: 'When would I use low diffusion?', a: 'Low diffusion works well on percussive sources where you want to hear the room character without smearing the transients. It is also useful for creating a more realistic small-room sound, where reflections are naturally sparser. On snare drums, low diffusion can add a distinctive "crack" to the reverb tail. For most vocal and instrument mixing, medium-to-high diffusion sounds more polished.' },
                { q: 'How does diffusion relate to the Quality setting?', a: 'The Quality setting in Ableton\'s Reverb controls the density of the algorithm\'s internal processing. Higher quality increases the number of calculated reflections, which interacts with the diffusion setting. At low quality, even high diffusion can sound slightly grainy. At high quality, the reverb tail is smoother and more realistic, but uses more CPU. For final mixing, use the highest quality setting.' },
            ],
        },
        {
            id: 'damping',
            label: 'F',
            zone: { left: 67, width: 14 },
            color: '#B85A3F',
            level: 'advanced',
            name: 'Damping',
            matchClue: 'Controls how quickly high and low frequencies fade within the reverb tail compared to the mid frequencies.',
            description: 'Damping controls the frequency-dependent decay within the reverb. The high shelf determines how quickly high frequencies fade: higher damping means brightness fades faster, creating a warmer, more natural reverb (real rooms absorb high frequencies through soft furnishings, air, and surfaces). The low shelf controls bass decay: useful for preventing low-end rumble from building up in the reverb tail. Together, they shape the tonal character of the space.',
            questions: [
                { q: 'Why do real rooms have high-frequency damping?', a: 'In a real acoustic space, high frequencies are absorbed more easily by soft materials (curtains, carpets, upholstery, even the air itself over long distances). This means high frequencies decay faster than low frequencies. A room with lots of soft furnishings has heavy high-frequency damping (warm, dark reverb). A room with hard surfaces (tile, concrete) has minimal damping (bright, harsh reverb). Simulating this makes digital reverb sound realistic.' },
                { q: 'How do I use damping to create different room characters?', a: 'For a warm, intimate room: increase high-frequency damping significantly: the reverb tail should darken quickly. For a bright, modern studio: reduce high-frequency damping. For a large concert hall: moderate high-frequency damping with the {{D}} decay set long. For a cathedral: very long decay with moderate damping. The combination of decay time and damping defines the character of the virtual space.' },
                { q: 'When should I use low-frequency damping?', a: 'Low-frequency damping is useful when the reverb tail has too much bass, causing muddiness in the mix. This is common with long {{D}} decay times, where bass frequencies can accumulate and overwhelm the reverb. Increasing the low shelf damping tightens the low end of the reverb, keeping it clear. It achieves a similar effect to the {{A}} input low-cut filter but works during the decay rather than at the input.' },
            ],
        },
        {
            id: 'dry-wet',
            label: 'G',
            zone: { left: 81, width: 19 },
            color: '#0891B2',
            level: 'foundation',
            name: 'Dry/Wet',
            matchClue: 'The balance between the original unprocessed signal and the reverb effect.',
            description: 'Controls the mix between the dry (original, unprocessed) signal and the wet (reverb) signal. At 0%, you hear only the dry signal, no reverb. At 100%, you hear only the reverb: no direct sound. For mixing, the reverb is typically used on a send/return channel at 100% wet, with the send level controlling how much reverb each track gets. When used as an insert effect, 10-30% wet is typical for subtle ambience.',
            questions: [
                { q: 'What is the difference between using reverb on a send versus an insert?', a: 'On a send/return, the reverb is set to 100% wet and multiple tracks share the same reverb. You control each track\'s reverb amount with its send level. This is more efficient and creates a cohesive sense of space. On an insert, the reverb processes only that track and the Dry/Wet knob blends the effect. Sends are the standard professional approach for most mixing scenarios.' },
                { q: 'How much reverb should I use?', a: 'Less than you think. A common beginner mistake is using too much reverb, which pushes sounds back in the mix and creates a washy, undefined sound. Start with the Dry/Wet at 0% and slowly increase until you can just hear the reverb adding space and depth, then back off slightly. If you can obviously hear the reverb as a separate effect, it is probably too much for most mixing contexts.' },
                { q: 'When would I use 100% wet?', a: 'Use 100% wet when the reverb is on a send/return channel (the standard approach), because the dry signal is already coming from the original track. Also use 100% wet for creative effects: fully wet reverb with a long {{D}} decay and no dry signal creates an ethereal, ambient wash that works beautifully for pads, background textures, or special effects like reverse reverb.' },
            ],
        },
    ],
};

export default reverbConfig;
